### PR TITLE
Not fail analysis if Node is not available

### LINKED ISSUE #69: Do not fail analysis if Node is not available

### PR DESCRIPTION
**Pull request by vilchik-elena**
fix #69

### CODE REVIEW

File: sonar-css-plugin/src/main/java/org/sonar/css/plugin/CssRuleSensor.java [hunk 1]
```diff
@@ -89,6 +99,39 @@ public void execute(SensorContext context) {
...
 
+  private boolean checkCompatibleNodeVersion(SensorContext context) {
+    String nodeExecutable = linterCommandProvider.nodeExecutable(context.config());
+    LOG.debug("Checking node version");
+    String messageSuffix = "No CSS files will be analyzed.";
+
+    String version;
+    try {
+      Process process = Runtime.getRuntime().exec(nodeExecutable + " -v");
+      version = IOUtils.toString(process.getInputStream(), StandardCharsets.UTF_8).trim();
```
Comment (Evangelink) [inline sonar-css-plugin/src/main/java/org/sonar/css/plugin/CssRuleSensor.java]: Don't we have the encoding as a parameter? Shouldn't we use the value here instead of forcing UTF8?

File: sonar-css-plugin/src/main/java/org/sonar/css/plugin/StylelintCommandProvider.java [hunk 2]
```diff
@@ -50,4 +52,9 @@
   public String configPath(File deployDestination) {
     return new File(deployDestination, CONFIG_PATH).getAbsolutePath();
   }
+
+  @Override
+  public String nodeExecutable(Configuration configuration) {
```
Comment (Evangelink) [inline sonar-css-plugin/src/main/java/org/sonar/css/plugin/StylelintCommandProvider.java]: Do you really need to take the `Configuration` as parameter?

File: sonar-css-plugin/src/test/java/org/sonar/css/plugin/CssRuleSensorTest.java [hunk 3]
```diff
@@ -80,6 +86,20 @@ public void test_execute() throws IOException {
     assertThat(Files.readAllLines(configPath)).containsOnly("{\"rules\":{\"color-no-invalid-hex\":true}}");
   }
 
+  @Test
+  public void test_invalid_node() throws IOException {
```
Comment (Evangelink) [inline sonar-css-plugin/src/test/java/org/sonar/css/plugin/CssRuleSensorTest.java]: That may be too difficult but it would be nice to be able to test the different failure cases:

- Node not found
- Invalid version
- Invalid version format

File: sonar-css-plugin/src/main/java/org/sonar/css/plugin/CssRuleSensor.java (hunk 1 above)
Comment (vilchik-elena) [reply sonar-css-plugin/src/main/java/org/sonar/css/plugin/CssRuleSensor.java]: as far as I understand, we are guaranteed to get UTF-8 in this case. And using parameter from sonar might be even worse, as it's supposed to be sources encoding.

File: sonar-css-plugin/src/main/java/org/sonar/css/plugin/StylelintCommandProvider.java (hunk 2 above)
Comment (vilchik-elena) [reply sonar-css-plugin/src/main/java/org/sonar/css/plugin/StylelintCommandProvider.java]: indeed we don't need it now, but I copy pasted SonarTS and left it for #44

File: sonar-css-plugin/src/test/java/org/sonar/css/plugin/CssRuleSensorTest.java (hunk 3 above)
Comment (vilchik-elena) [reply sonar-css-plugin/src/test/java/org/sonar/css/plugin/CssRuleSensorTest.java]: done
