### PR TITLE
S4670: add parameter for ignored types

### LINKED ISSUE #181: S4670: add parameter for ignored types
In #151 there was reported an exception for Angular Material, and we hardcoded that exception in the plugin. Yet there are other libraries declaring types (e.g. [FontAwesome](https://community.sonarsource.com/t/css-s4670-the-use-of-fontawesome-raises-a-issue/10114)), so probably it makes sense to expose that parameter to the user.

### PR DESCRIPTION
**Pull request by vilchik-elena**
fixes #181

### CODE REVIEW

File: sonar-css-plugin/src/main/java/org/sonar/css/plugin/rules/CssRule.java [hunk 1]
```diff
@@ -29,4 +31,9 @@
   default List<Object> stylelintOptions() {
     return Collections.emptyList();
   }
+
+  default List<String> split(String parameterValue) {
```
Comment (saberduck) [inline sonar-css-plugin/src/main/java/org/sonar/css/plugin/rules/CssRule.java]: I think this could be moved into some `Utils` class instead of adding it into this interface. And I would maybe call it `splitAndTrim`.
Also perhaps you can separate this change from adding the parameter itself?

File: sonar-css-plugin/src/main/java/org/sonar/css/plugin/rules/CssRule.java [hunk 2]
```diff
@@ -29,4 +31,9 @@
...
+    String[] split = parameterValue.split(",");
+    return Arrays.stream(split).map(value -> value.trim()).collect(Collectors.toList());
```
Comment (saberduck) [inline sonar-css-plugin/src/main/java/org/sonar/css/plugin/rules/CssRule.java]: You can use `String::trim` lambda as argument to `map`
