### PR TITLE
S4654: Avoid FPs for unknown property inside :export/:import selectors

### LINKED ISSUE #258: Avoid false-positive for unknown property (S4654) inside :export selector
I am experiencing an issue similar to #149 and #152, and I believe that PR #171 has not properly fixed the issue. I have something like the following in `_variables.scss`: 
```
$light-blue-10: #c0e7f3;
$light-blue-40: #4bc7e7;
$teal: #23B8A7;
:export {
    lightBlue10: $light-blue-10;
    lightBlue40: $light-blue-40;
    teal: $teal;
}
```
This causes a blocker violation for each exported property, e.g.:
```
Unexpected unknown property "lightBlue10"
```

The original fix added [a pseudo-selector exclusion for "export" and "import"](https://github.com/SonarSource/sonar-css/pull/171/files#diff-d447676eaf4c8790e45ed6ae609894caR42), but I believe we also need a selector exclusion for these within the `property-no-unknown` rule as indicated in the [Stylelint docs](https://stylelint.io/user-guide/rules/property-no-unknown#ignoreselectors-regex-regex-string). 

The [exclusion of specific example property values `exportedKey` and `localAlias`](https://github.com/SonarSource/sonar-css/pull/171/files#diff-0fbf01c6609b6582d0d4d15b7602df4aR42) in the original PR, while not hurting anything, doesn't seem to be helping either. I believe that removing these exclusions while also adding the property selector exclusion will lead to the same result but be more flexible in terms of the actual property names.

### PR DESCRIPTION
**Pull request by guillaume-dequenne-sonarsource**
fixes #258

### CODE REVIEW

File: sonar-css-plugin/src/main/java/org/sonar/css/plugin/rules/PropertyNoUnknown.java [hunk 1]
```diff
@@ -31,30 +31,39 @@
 @Rule(key = "S4654")
 public class PropertyNoUnknown implements CssRule {
 
-  private static final String DEFAULT_IGNORED_PROPERTIES = "composes, exportedKey, localAlias, /^mso-/";
+  private static final String DEFAULT_IGNORED_PROPERTIES = "composes, /^mso-/";
+  private static final String DEFAULT_IGNORED_SELECTORS = "/export/, /import/";
```
Comment (andrea-guarino-sonarsource) [inline sonar-css-plugin/src/main/java/org/sonar/css/plugin/rules/PropertyNoUnknown.java:35]: shouldn't it be with a leading `:`? `:export` and `:import`?

Comment (guillaume-dequenne-sonarsource) [reply sonar-css-plugin/src/main/java/org/sonar/css/plugin/rules/PropertyNoUnknown.java:35]: That's what I used at the beginning, without regex, but as I saw it raise on `:import("path/to/dep.css")` from `cssModules.css` in our ITs, I decided to just make it a little more permissive and simply exempt any selector containing `export` or `import`.

Do you think we should restrict the exemption to cases with the leading `:` instead?

Comment (andrea-guarino-sonarsource) [reply sonar-css-plugin/src/main/java/org/sonar/css/plugin/rules/PropertyNoUnknown.java:35]: ah I see, I think I would modify it as `/^:export.*/` and `/^:import.*/`, just to avoid raising on unrelated selectors like `my-export-class`

Comment (guillaume-dequenne-sonarsource) [reply sonar-css-plugin/src/main/java/org/sonar/css/plugin/rules/PropertyNoUnknown.java]: Good point, I just updated the regex in https://github.com/SonarSource/sonar-css/pull/327/commits/b3c1b3d5e5487b38b90f195a144b218cdaf46dff and added a relevant test case in ruling.

**Review by andrea-guarino-sonarsource — APPROVED** [review]
