### PR TITLE
Not fail analysis when syntax error

### LINKED ISSUE #67: Not fail analysis when syntax error

### PR DESCRIPTION
**Pull request by vilchik-elena**
Fix #67

### CODE REVIEW

File: sonar-css-plugin/src/main/java/org/sonar/css/plugin/CssRuleSensor.java [hunk 1]
```diff
@@ -150,32 +150,42 @@ private static String normalizeMessage(String message) {
...
+      .on(inputFile)
+      .at(inputFile.selectLine(issue.line))
+      .message(normalizeMessage(issue.text));
+
+    RuleKey ruleKey = cssRules.getActiveSonarKey(issue.rule);
+    if (ruleKey == null) {
+      if ("CssSyntaxError".equals(issue.rule)) {
+        LOG.error("Failed to parse " + inputFile.uri());
+      } else {
+        LOG.error("Unknown stylelint rule or rule not enabled " + issue.rule);
```
Comment (Evangelink) [inline sonar-css-plugin/src/main/java/org/sonar/css/plugin/CssRuleSensor.java]: I haven't seen any test covering this line. Is there one?

File: sonar-css-plugin/src/main/java/org/sonar/css/plugin/CssRuleSensor.java [hunk 2]
```diff
@@ -150,32 +150,42 @@ private static String normalizeMessage(String message) {
...
+          saveIssue(context, inputFile, issue);
         }
       }
     }
   }
 
+  private void saveIssue(SensorContext context, InputFile inputFile, Issue issue) {
+    NewIssue sonarIssue = context.newIssue();
+
+    NewIssueLocation location = sonarIssue.newLocation()
```
Comment (Evangelink) [inline sonar-css-plugin/src/main/java/org/sonar/css/plugin/CssRuleSensor.java]: There is no need to create this so early. IMO it should be done only in the else part.
