### PR TITLE
Record warning when nodejs not available DO NOT MERGE

### LINKED ISSUE #123: Record a warning when Node.js is not available to perform the analysis of CSS files
The following warning should be recorded using plugin API when Node.js is not detected and therefore the analysis of CSS file can not occur.

```
CSS files not analysed because Node.js environment is missing when analyzing the source code
```

### Implementation notes

This work depends on new features in the SonarQube API. It can be merged after the API changes are part of a milestone / stable release (ETA Sep 28).
**Update:** the new ETA is Oct 10.

Warning messages implemented:

> CSS files were not analyzed. Only Node.js v6 or later is supported, got vTHE_VERSION.

> CSS files were not analyzed. Failed to parse Node.js version, got 'THE_OUTPUT'.

>CSS files were not analyzed. Node.js could not be detected using command: THE_COMMAND. Please check your build environment or the analysis parameters to fix the issue.

### PR DESCRIPTION
**Pull request by janos-ss**
fixes #123 

Notes for manual testing, easy ways to trigger the 3 kinds of warnings:

- `sonar-scanner -Dsonar.css.node=/tmp` (not a file)
- `sonar-scanner -Dsonar.css.node=/tmp/old` where `/tmp/old` is a shell script with a simple `echo` of an unsupported old version, for example `echo v5.11.1`
- `sonar-scanner -Dsonar.css.node=/tmp/rubbish` where `/tmp/rubbish` is a shell script with a simple `echo rubbish`

### Implementation notes

This work depends on new features in the SonarQube API. It can be merged after the API changes are part of a milestone / stable release (ETA Sep 28).

**Update:** the new ETA is Oct 10.

### CODE REVIEW

File: sonar-css-plugin/src/main/java/org/sonar/css/plugin/CssRuleSensor.java [hunk 1]
```diff
@@ -135,13 +144,19 @@ private boolean checkCompatibleNodeVersion(SensorContext context) {
     if (versionMatcher.matches()) {
       int major = Integer.parseInt(versionMatcher.group(1));
       if (major < MIN_NODE_VERSION) {
-        String message = String.format("Only Node.js v%s or later is supported, got %s. %s", MIN_NODE_VERSION, version, messageSuffix);
-        LOG.error(message);
+        String message = String.format("Only Node.js v%s or later is supported, got %s.", MIN_NODE_VERSION, version);
```
Comment (vilchik-elena) [inline sonar-css-plugin/src/main/java/org/sonar/css/plugin/CssRuleSensor.java]: You don't need to keep the old message if you think that another one fits better for UI warning.

File: sonar-css-plugin/src/main/java/org/sonar/css/plugin/CssRuleSensor.java [hunk 2]
```diff
@@ -135,13 +144,19 @@ private boolean checkCompatibleNodeVersion(SensorContext context) {
...
+        LOG.error(message + ' ' + messageSuffix);
```
Comment (vilchik-elena) [inline sonar-css-plugin/src/main/java/org/sonar/css/plugin/CssRuleSensor.java]: How about adding method to sensor which does both: logging and adding warning

File: sonar-css-plugin/src/main/java/org/sonar/css/plugin/AnalysisWarningsWrapper.java [hunk 3]
```diff
@@ -0,0 +1,43 @@
...
+import org.sonar.api.notifications.AnalysisWarnings;
+
+/**
+ * Wrap an AnalysisWarnings instance, available since SQ API 7.4.
+ * Do not load this class on older runtimes.
+ * Drop this class when the minimum supported version of SonarJava reaches 7.4.
+ */
+@ScannerSide
+@InstantiationStrategy("PER_BATCH")
+public class AnalysisWarningsWrapper {
```
[the remark this answers is not in the document]
Comment (janos-ss) [reply sonar-css-plugin/src/main/java/org/sonar/css/plugin/AnalysisWarningsWrapper.java]: Do you mean to make the wrapper an interface, and then conditionally add either the implementation using the new API, or a no-op implementation for old SQ?

That was actually my original approach when I did the implementation for SonarJava. Nico asked me to rewrite using the current approach. (His reasoning, roughly: that approach requires an interface + a no-op implementation + more tests.)

If you meant something else, please let me know. If you still prefer that I rewrite, not a problem, just let me know.

File: sonar-css-plugin/src/main/java/org/sonar/css/plugin/CssRuleSensor.java (hunk 2 above)
Comment (janos-ss) [reply sonar-css-plugin/src/main/java/org/sonar/css/plugin/CssRuleSensor.java]: The warnings for the UI should follow different guidelines from what we use in log messages. These warnings must be especially user-friendly, and actionable, and keep in mind that they will be shown out of context, the logs not being visible. So we expressly don't want to mix log messages and these warnings.

File: sonar-css-plugin/src/main/java/org/sonar/css/plugin/CssRuleSensor.java (hunk 1 above)
Comment (janos-ss) [reply sonar-css-plugin/src/main/java/org/sonar/css/plugin/CssRuleSensor.java]: I don't know how to phrase it well for both purposes at the same time: the log messages use future tense "CSS won't be analyzed" and that's good. On SQ UI that will look weird, there past tense makes sense. It's easier to just write two versions. Which is good for another reason, because as I explain in a response to another of your comments, the UI messages need to be worded differently from log messages.

In any case, I'm open to ideas!

File: sonar-css-plugin/src/main/java/org/sonar/css/plugin/AnalysisWarningsWrapper.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (vilchik-elena) [reply sonar-css-plugin/src/main/java/org/sonar/css/plugin/AnalysisWarningsWrapper.java]: Indeed that what I meant. And I just realized that we need this "compatibility" not only for old SQ but also for SonarLint. Endless null checks in sensor are confusing me the most in fact. So I think the best way to go, is just extract adding warning with null check in another method
